name: treino_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ícones do Cupertino para iOS
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Adicione aqui qualquer outra dependência necessária no futuro

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Adiciona a imagem de fundo para o projeto
  assets:
    - assets/images/background_fitness.jpg

  # Adiciona fontes customizadas, se necessário no futuro
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
